"""Initial migration

Revision ID: 3a2c277e2ed4
Revises: 
Create Date: 2024-10-28 14:47:30.515288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2c277e2ed4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('bet_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', name='betstatus'), nullable=False),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_index(op.f('ix_bets_bet_id'), 'bets', ['bet_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('coefficient', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='eventstate'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_bets_bet_id'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
